### ISSUE TITLE
Animations: "this.spriteSheet is undefined"

### ISSUE THREAD

**Issue by Elfangor93** [creative-connections/Bodylight.js-Composer#20]
How can I cerate Composer compatible Animations with Adobe Animate CC. I get always the message "this.spriteSheet is undefined" when I try to import animations exportet from Adobe Animate...
![grafik](https://user-images.githubusercontent.com/39154009/55218514-a0a39c80-5202-11e9-8708-67acd6787551.png)

**Comment by david-polak** [comment]
In the `publish settings` disable every one of these checkboxes and try again.

<img width="332" alt="publish-settings" src="https://user-images.githubusercontent.com/5686338/55228804-5844a880-521b-11e9-88e7-29ccd11af63f.png">

Animate documentation isn't written yet, so shortly, name your timeline containing objects `name_anim` to show in the composer as animation or `name_text` if text and `name_play` if it should play without any control in composer.

**Comment by david-polak** [comment]
@19leunam93 did disabling the checkboxes fix the issue?

**Comment by Elfangor93** [comment]
By following your grafical manual on google drive it works with the animations...
