### ISSUE TITLE
Simulations dont start at zero-time after resetModel

### ISSUE THREAD

**Issue by Elfangor93** [creative-connections/Bodylight.js-Composer#21]
With this Model (see attachement), the model.reset(true,true) - Action dont works correctly. The model was created in OpenModelica, exported with OM Compiler and compiled to Javascript with FMU Compiler.
[BouncingBall.zip](https://github.com/creative-connections/Bodylight.js-Composer/files/3047252/BouncingBall.zip)

**Comment by david-polak** [comment]
Use 
![Screenshot_20190417_150350](https://user-images.githubusercontent.com/5686338/56289780-060fec80-6122-11e9-88e6-f931febfe064.png)
switch in the model configuration, it will create a new FMU instance on reset.
