### ISSUE TITLE
Toolbar on Plotly-Charts

### ISSUE THREAD

**Issue by Elfangor93** [creative-connections/Bodylight.js-Composer#23]
It would be nice to have the plotly-toolbar to analyze and save the chart, if it is a static model (model-mode: one shot):
![grafik](https://user-images.githubusercontent.com/39154009/56345924-2d69c680-61c1-11e9-87de-8f1b6cdd22bf.png)

To create useful tasks for the students, it is useful if there is a possibility to analyze and save the charts created by the model. Otherwise the plots in a "One shot - model" are not very useful in a learning environment. Plotly would provides such functionality. So why not showing this toolbar also in charts created by the composer?

**Comment by TomasKulhanek** [comment]
Good feature to be added into v2.0.

**Comment by TomasKulhanek** [comment]
plotly and toolbar enabled in https://github.com/creative-connections/aurelia-bodylight-plugin/releases/tag/v2.0.5
