### ISSUE TITLE
range.SetValue throws an exception during initialisation

### ISSUE THREAD

**Issue by filip-jezek** [creative-connections/Bodylight.js-Composer#53]
when 

getWidgetByName('init_rng').setValue('value', 0.1);

run in custom js it throws

VM37098 about:srcdoc:488 Uncaught (in promise) TypeError: Cannot set property 'value' of undefined
    at Range.setValue (VM20722 about:srcdoc:488)
    at javascript.onBeforeModelRun (VM20722 about:srcdoc:14355)
    at VM20722 about:srcdoc:14509
    at Array.forEach (<anonymous>)
    at VM20722 about:srcdoc:14509

It is not necessarily needed to use exactly this function, however simply set its value but other mean (e.g. this.getElementById.value = ...) do not work during initialization phase. Any workaround?

**Comment by david-polak** [comment]
I believe range has 'target' not 'value'

**Comment by filip-jezek** [comment]
YES!
