### ISSUE TITLE
High CPU utilization when simulator paused

### ISSUE THREAD

**Issue by TomasKulhanek** [creative-connections/Bodylight.js-Composer#56]
There is high CPU utilization when simulator is paused. There is not much difference between paused and non-paused simulator. 75% utilization vs. 95% utilization. If the tab with simulator is closed then utilization goes to normal 0%. Experienced in chrome and firefox.

[screenshot of utilization in firefox when paused](https://drive.google.com/open?id=1UF2zuBhZWqYSbDFTYkuEZp3UAW4frlIf)

[screenshot of utilization in chrome when paused](https://drive.google.com/open?id=1z_g5Iz7MwX1faSCDyr_wvMQUh28-d4EW)

Expected behavior is about 0% cpu utilization when simulator is paused/stopped.

**Comment by david-polak** [comment]
The Animate widget rendering is not paused by the model pause function, it is possible most of the cpu cycles are eaten by the animation. Remove animation from the scene and report results, I expect the utilization to drop to acceptable levels.

To solve this, it's necessary to also pause the Animate rendering function, currently there is no API method to achieve this.

**Comment by TomasKulhanek** [comment]
In v2.0 I'll consider 
```
request= requestAnimationFrame(performAnimation) 
... 
cancelAnimationFrame(request) 
```

**Comment by TomasKulhanek** [comment]
fixed in https://github.com/creative-connections/aurelia-bodylight-plugin
